---
- name: Database
  become: true
  become_user: postgres
  postgresql_db:
    name: decidedb

- name: Database user
  become: true
  become_user: postgres
  postgresql_user:
    db: decidedb
    name: decideuser
    password: decidepass123
    priv: ALL

